from typing import Iterator, Protocol, overload

import hawkey

class Package(Protocol):
    name: str
    version: str
    release: str
    epoch: int
    arch: str
    @property
    def sourcerpm(self) -> str: ...
    @property
    def requires(self) -> list[hawkey.Reldep]: ...
    @property
    def chksum(self) -> tuple[int, bytes]: ...
    def remote_location(self, schemes: tuple[str, ...] | list[str] = ...) -> str | None: ...

class Query:
    def __iter__(self) -> Iterator[Package]: ...
    def filter(self, *flags: int, **criteria: str | int | hawkey.Reldep) -> "Query": ...
    def available(self) -> "Query": ...
    def latest(self, limit: int = -1) -> "Query": ...

class Sack:
    def query(self, flags: int = 0) -> Query: ...

class LibdnfRepo:
    def getRevision(self) -> int: ...
    def getMaxTimestamp(self) -> int: ...

class Repo:
    _repo: LibdnfRepo
    def remote_location(self, location: str, schemes: tuple[str, ...] = ...) -> str | None: ...

class RepoDict:
    def add_new_repo(self, repoid: str, conf: "conf.Conf", baseurl: tuple[str, ...] | list[str] = (), **kwargs: str | list[str]) -> Repo: ...
    def items(self) -> Iterator[tuple[str, Repo]]: ...

class Option:
    def getPriority(self) -> int: ...
    # SWIG exposes two overloads: positional (priority, value) for all Option
    # subclasses, and keyword (value=, priority=) for scalar options
    @overload
    def set(self, priority: int, value: str | list[str]) -> None: ...
    @overload
    def set(self, value: str, priority: int) -> None: ...

class StringList:
    def push_back(self, value: str) -> None: ...

class StringListOption(Option):
    def getValue(self) -> StringList: ...

class ConfigMain:
    def config_file_path(self) -> Option: ...
    def reposdir(self) -> Option: ...
    def persistdir(self) -> Option: ...
    def system_cachedir(self) -> Option: ...
    def varsdir(self) -> Option: ...
    def optional_metadata_types(self) -> StringListOption: ...

class Substitutions(dict[str, str]):
    ...

class conf:
    class Conf:
        _config: ConfigMain
        substitutions: Substitutions

class BaseConf:
    substitutions: Substitutions

class Base:
    conf: BaseConf
    sack: Sack
    repos: RepoDict
    def __init__(self, conf: conf.Conf | None = None) -> None: ...
    def fill_sack(self, load_system_repo: bool = True, load_available_repos: bool = True) -> None: ...

class rpm:
    @staticmethod
    def basearch(arch: str) -> str: ...
